@echo off
echo Starting BKD Advisors Website...
echo.
cd /d "%~dp0"
echo Checking for dependencies...
if not exist "node_modules" (
    echo Installing dependencies (this may take a minute)...
    call npm install
)
echo Starting development server...
call npm run dev
pause
